-- +migrate Up
INSERT INTO stock(symbol, name, created_at) VALUES
    ('T', 'AT&T, Inc.', CURRENT_TIMESTAMP),
    ('WMT', 'Wal-Mart Stores Inc.', CURRENT_TIMESTAMP),
    ('PYPL', 'PayPal Holdings, Inc.', CURRENT_TIMESTAMP),
    ('TWTR', 'Twitter, Inc.', CURRENT_TIMESTAMP),
    ('NFLX', 'Netflix, Inc.', CURRENT_TIMESTAMP),
    ('FB', 'Facebook Inc.', CURRENT_TIMESTAMP),
    ('NKE', 'Nike, Inc.', CURRENT_TIMESTAMP),
    ('GOOG', 'Alphabet Inc.', CURRENT_TIMESTAMP),
    ('SNAP', 'Snap Inc.', CURRENT_TIMESTAMP),
    ('F', 'Ford Motor Company', CURRENT_TIMESTAMP),
    ('V', 'Visa Inc.', CURRENT_TIMESTAMP),
    ('AMD', 'Advanced Micro Devices, Inc.', CURRENT_TIMESTAMP),
    ('BIDU', 'Baidu, Inc.', CURRENT_TIMESTAMP),
    ('MON', 'Monsanto Company', CURRENT_TIMESTAMP),
    ('S', 'Sprint Corporation', CURRENT_TIMESTAMP),
    ('M', 'Macy''s Inc', CURRENT_TIMESTAMP),
    ('C', 'Citigroup, Inc.', CURRENT_TIMESTAMP),
    ('JPM', 'JP Morgan Chase & Co.', CURRENT_TIMESTAMP),
    ('GM', 'General Motors Company', CURRENT_TIMESTAMP),
    ('HPQ', 'HP Inc.', CURRENT_TIMESTAMP),
    ('PG', 'Procter & Gamble Company', CURRENT_TIMESTAMP),
    ('SQ', 'Square, Inc.', CURRENT_TIMESTAMP),
    ('NEWR', 'New Relic, Inc.', CURRENT_TIMESTAMP),
    ('OKTA', 'Okta, Inc.', CURRENT_TIMESTAMP),
    ('SPLK', 'Splunk Inc.', CURRENT_TIMESTAMP),
    ('EBAY', 'eBay Inc.', CURRENT_TIMESTAMP),
    ('TSLA', 'Tesla, Inc.', CURRENT_TIMESTAMP),
    ('ACN', 'Accenture plc', CURRENT_TIMESTAMP),
    ('NVDA', 'NVIDIA Corporation', CURRENT_TIMESTAMP),
    ('AMZN', 'Amazon.com, Inc.', CURRENT_TIMESTAMP),
    ('INTC', 'Intel Corporation', CURRENT_TIMESTAMP),
    ('AAPL', 'Apple Inc.', CURRENT_TIMESTAMP),
    ('CSCO', 'Cisco Systems, Inc.', CURRENT_TIMESTAMP),
    ('FIT', 'Fitbit, Inc.', CURRENT_TIMESTAMP),
    ('BABA', 'Alibaba Group Holding Limited', CURRENT_TIMESTAMP),
    ('ORCL', 'Oracle Corporation', CURRENT_TIMESTAMP),
    ('UA', 'Under Armour, Inc.', CURRENT_TIMESTAMP),
    ('GE', 'General Electric Company', CURRENT_TIMESTAMP),
    ('DIS', 'Walt Disney Company', CURRENT_TIMESTAMP),
    ('VZ', 'Verizon Communications Inc.', CURRENT_TIMESTAMP),
    ('BA', 'Boeing Company', CURRENT_TIMESTAMP),
    ('CRM', 'Salesforce.com Inc.', CURRENT_TIMESTAMP),
    ('KO', 'Coca-Cola Company', CURRENT_TIMESTAMP),
    ('GPRO', 'GoPro, Inc.', CURRENT_TIMESTAMP);

-- +migrate Down
DELETE FROM stock 
WHERE symbol IN (
    'T',
    'WMT',
    'PYPL',
    'TWTR',
    'NFLX',
    'FB',
    'NKE',
    'GOOG',
    'SNAP',
    'F',
    'V',
    'AMD',
    'BIDU',
    'MON',
    'S',
    'M',
    'C',
    'JPM',
    'GM',
    'HPQ',
    'PG',
    'SQ',
    'NEWR',
    'OKTA',
    'SPLK',
    'EBAY',
    'TSLA',
    'ACN',
    'NVDA',
    'AMZN',
    'INTC',
    'AAPL',
    'CSCO',
    'FIT',
    'BABA',
    'ORCL',
    'UA',
    'GE',
    'DIS',
    'VZ',
    'BA',
    'CRM',
    'KO',
    'GPRO'
);
